# Font style metadata
name = "dm-serif-text"

# Optional Google font URL
google_fonts = "DM+Serif+Text|Cutive+Mono|Raleway:300,400,500,600"

# Font families
heading_font = "DM Serif Text"
body_font = "Raleway"
nav_font = "Raleway"
mono_font = "Cutive Mono"

# Font size
font_size = "20"
font_size_small = "16"
